language: java
sudo: true
dist: trusty
jdk: oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - chmod +x mvnw
  # Travis CI 서버의 Home
cache:
  directories:
    - $HOME/.m2
    - $HOME/.mvnw
script: "./mvnw clean package"

before_deploy:
 - zip -r studyhelper_ec2 ./*
 - mkdir -p deploy
 - mv studyhelper_ec2.zip deploy/studyhelper_ec2.zip

deploy:
 - provider: s3
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key: $AWS_SECRET_KEY
   
   bucket: studyhelper-ec2
   region: ap-northeast-2
   skip_cleanup: true
   acl: private
   local_dir: deploy
   wait_until_deployed : true
   on:
      repo: byeunsungjae/studyhelper_ec2
      branch: master

 - provider: codedeploy
   access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
   secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
   bucket: studyhelper-ec2 # S3 버킷
   key: studyhelper_ec2.zip # S3 버킷에 저장된 springboot-webservice.zip 파일을 EC2로 배포
   bundle_type: zip
   application: studyhelper-ec2 # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
   deployment_group: studyhelper-ec2-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
   region: ap-northeast-2
   wait-until-deployed: true
   on:
      repo: byeunsungjae/studyhelper_ec2
      branch: master
# CI 실행 완료 시 메일로 알람보내기
notifications:
 email:
   recipients:
     - dfdo333@gmail.com