language: java
sudo: true
dist: trusty
jdk: oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - chmod +x mvnw
  # Travis CI 서버의 Home
cache:
  directories:
    - $HOME/.m2
    - $HOME/.mvnw
script: "./mvnw clean package"