language: java
sudo: true
dist: trusty
jdk: oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - chmod +x mvnw
  # Travis CI 서버의 Home
cache:
  directories:
    - $HOME/.m2
    - $HOME/.mvnw
script: "./mvnw clean package"

before_deploy:
  - zip -r studyhelper_ec2 *
  - mkdir -p deploy
  - mv studyhelper_ec2.zip deploy/studyhelper-ec2.zip

deploy:
 - provider: s3
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key: $AWS_SECRET_KEY

   bucket: studyhelper-ec2
   region: ap-northeast-2
   skip_cleanup: true
   acl: public_read
   local_dir: deploy
   wait_until_deployed : true
   on:
      repo:  byeunsungjae/studyhelper_ec2
      branch: master
      
   

# CI 실행 완료 시 메일로 알람
notifications:
 email:
   recipients:
     - dfdo333@gmail.com