spring:
  profiles: travis
  datasource:
    url: ${url:url}
    username: ${username:username}
    password: ${password:password}
    driver-class-name: ${drivername:dbname}
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true